# This rule is not used by the project cnpg-storage-manager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cnpg.supporttools.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cnpg-storage-manager
    app.kubernetes.io/managed-by: kustomize
  name: storagepolicy-viewer-role
rules:
- apiGroups:
  - cnpg.supporttools.io
  resources:
  - storagepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cnpg.supporttools.io
  resources:
  - storagepolicies/status
  verbs:
  - get
